Avoid google indexing
MuckRock/documentcloud pull request #130
Opened 2022-10-06 21:13 UTC by jimkang

This is the first part of the implementation of the de-indexing feature. This adds a boolean (defaulting to false) to documents that indicates that a document should not be indexed by Google. This goes along with [this corresponding PR in the web app](https://github.com/MuckRock/documentcloud-frontend/pull/100).

2022-10-11 13:21 UTC, mitchelljkotler requested changes
You will also want to edit `documents/admin.py` so that staff can update the no index field from the Django admin.

2022-10-11 13:27 UTC, mitchelljkotler requested changes
Also - it was requested that these documents be removed from public searches on DocumentCloud as well.  That would require adding the field to the Solr index and filtering on it for unauthenticated searches.  We would want to try and do this in a way that does not require a full re-index of the documents.  Dealing with Solr is not straight forward, so I can help explain how Solr works and how to accomplish this.

2022-10-11 13:27 UTC, mitchelljkotler commented on documentcloud/documents/tests/test_views.py
> +        assert document.hide_from_google is True
I would prefer:
`assert document.hide_from_google`

2022-10-12 20:00 UTC, jimkang commented on documentcloud/documents/models.py
> +    hide_from_google = models.BooleanField(
I think that's sort of confusing because we're also going to implement a feature to avoid Solr indexing. Maybe `hide_from_search_engines`?

2022-10-13 13:01 UTC, mitchelljkotler commented on documentcloud/documents/models.py
> +    hide_from_google = models.BooleanField(
1. There will only be one field which controls both search engine indexing and Solr indexing
2. The meta tag for search engines is called `noindex`
3. This is what I named it in MuckRock:
https://github.com/MuckRock/muckrock/blob/master/muckrock/foia/models/request.py#L188

2022-10-14 19:41 UTC, jimkang commented
@mitchelljkotler Updated in light of the comments so far.

2022-10-21 14:17 UTC, mitchelljkotler commented on documentcloud/documents/views.py
> +            del field_updates["noindex"]
"noindex" is not guaranteed to be set, this should be checked:
```
if "noindex" in field_updates:
    del ...
```

2022-12-01 14:23 UTC, merged